[YouTube]
enabled = true
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Theme'"
included-patches = "'MaterialYou' 'Return YouTube Username'"
version = "20.07.39"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"


[YouTube-Extended]
enabled = true
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Theme'"
included-patches = "'MaterialYou' 'Return YouTube Username'"
version = "19.47.53"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"
apkmirror-dpi = "120-640dpi"
uptodown-dpi = "nodpi"



[Music-Extended]
enabled = false
app-name = "YouTube Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patches-version = "dev"

[Spotify]
enabled = true
app-name = "Spotify"
arch = "arm64-v8a"
version = "latest"
included-patches = """\
    'Unlock Spotify Premium' \
    'Spoof signature' \
    """
uptodown-dlurl = "https://spotify.de.uptodown.com/android"


[Instagram]
enabled = false
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"

[Tiktok]
enabled = false
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
version = "36.5.4"

[Twitter]
enabled = false
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter"
uptodown-dlurl = "https://twitter.de.uptodown.com/android"
version = "10.84.0-release.0"
apkmirror-dpi = "120-640dpi"  
